const SHOW_ABOUT_MODAL = 'app/main-page/SHOW_ABOUT_MODAL';
const HIDE_ABOUT_MODAL = 'app/main-page/HIDE_ABOUT_MODAL';
const TOGGLE_SIDEBAR = 'app/main-page/TOGGLE_SIDEBAR';
const HIDE_SIDEBAR = 'app/main-page/HIDE_SIDEBAR';

export {
  SHOW_ABOUT_MODAL,
  TOGGLE_SIDEBAR,
  HIDE_ABOUT_MODAL,
  HIDE_SIDEBAR
}